<a href="https://colab.research.google.com/github/atharavkalore10/pandaslibrary/blob/main/SpecialTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as nb
import pandas as pd
from google.colab import files
uploded = files.upload()
filepath ='/content/Spotify Most Streamed Songs.csv'
df = pd.read_csv(filepath)

Saving Spotify Most Streamed Songs.csv to Spotify Most Streamed Songs.csv

In [2]:
df

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,cover_url
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,B,Major,80,89,83,31,0,8,4,Not Found
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,C#,Major,71,61,74,7,0,10,4,https://i.scdn.co/image/ab67616d0000b2730656d5...
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,F,Major,51,32,53,17,0,31,6,https://i.scdn.co/image/ab67616d0000b273e85259...
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,A,Major,55,58,72,11,0,11,15,https://i.scdn.co/image/ab67616d0000b273e787cf...
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,A,Minor,65,23,80,14,63,11,6,https://i.scdn.co/image/ab67616d0000b273ab5c9c...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,A,Major,60,24,39,57,0,8,3,https://i.scdn.co/image/ab67616d0000b2730f5397...
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,F#,Major,42,7,24,83,1,12,6,https://i.scdn.co/image/ab67616d0000b273e0b60c...
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,C#,Major,80,81,67,4,0,8,6,Not Found
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,C#,Major,82,67,77,8,0,12,5,Not Found
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,E,Minor,61,32,67,15,0,11,5,https://i.scdn.co/image/ab67616d0000b273992a1f...

In [3]:
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,cover_url
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,B,Major,80,89,83,31,0,8,4,Not Found
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,C#,Major,71,61,74,7,0,10,4,https://i.scdn.co/image/ab67616d0000b2730656d5...
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,F,Major,51,32,53,17,0,31,6,https://i.scdn.co/image/ab67616d0000b273e85259...
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,A,Major,55,58,72,11,0,11,15,https://i.scdn.co/image/ab67616d0000b273e787cf...
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,A,Minor,65,23,80,14,63,11,6,https://i.scdn.co/image/ab67616d0000b273ab5c9c...

In [4]:
df.tail()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,cover_url
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,A,Major,60,24,39,57,0,8,3,https://i.scdn.co/image/ab67616d0000b2730f5397...
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,F#,Major,42,7,24,83,1,12,6,https://i.scdn.co/image/ab67616d0000b273e0b60c...
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,C#,Major,80,81,67,4,0,8,6,Not Found
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,C#,Major,82,67,77,8,0,12,5,Not Found
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,E,Minor,61,32,67,15,0,11,5,https://i.scdn.co/image/ab67616d0000b273992a1f...

In [5]:
df.shape

(953, 25)

In [6]:
df.columns

Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts',
       'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts', 'bpm',
       'key', 'mode', 'danceability_%', 'valence_%', 'energy_%',
       'acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%',
       'cover_url'],
      dtype='object')

In [7]:
df.info

<bound method DataFrame.info of                               track_name      artist(s)_name  artist_count  \
0    Seven (feat. Latto) (Explicit Ver.)    Latto, Jung Kook             2
1                                   LALA         Myke Towers             1
2                                vampire      Olivia Rodrigo             1
3                           Cruel Summer        Taylor Swift             1
4                         WHERE SHE GOES           Bad Bunny             1
..                                   ...                 ...           ...
948                         My Mind & Me        Selena Gomez             1
949            Bigger Than The Whole Sky        Taylor Swift             1
950                 A Veces (feat. Feid)  Feid, Paulo Londra             2
951                        En La De Ella  Feid, Sech, Jhayco             3
952                                Alone           Burna Boy             1

     released_year  released_month  released_day  in_spotify_playlists  \
0             2023               7            14                   553
1             2023               3            23                  1474
2             2023               6            30                  1397
3             2019               8            23                  7858
4             2023               5            18                  3133
..             ...             ...           ...                   ...
948           2022              11             3                   953
949           2022              10            21                  1180
950           2022              11             3                   573
951           2022              10            20                  1320
952           2022              11             4                   782

     in_spotify_charts    streams  in_apple_playlists  ...  key   mode  \
0                  147  141381703                  43  ...    B  Major
1                   48  133716286                  48  ...   C#  Major
2                  113  140003974                  94  ...    F  Major
3                  100  800840817                 116  ...    A  Major
4                   50  303236322                  84  ...    A  Minor
..                 ...        ...                 ...  ...  ...    ...
948                  0   91473363                  61  ...    A  Major
949                  0  121871870                   4  ...   F#  Major
950                  0   73513683                   2  ...   C#  Major
951                  0  133895612                  29  ...   C#  Major
952                  2   96007391                  27  ...    E  Minor

     danceability_% valence_%  energy_% acousticness_% instrumentalness_%  \
0                80        89        83             31                  0
1                71        61        74              7                  0
2                51        32        53             17                  0
3                55        58        72             11                  0
4                65        23        80             14                 63
..              ...       ...       ...            ...                ...
948              60        24        39             57                  0
949              42         7        24             83                  1
950              80        81        67              4                  0
951              82        67        77              8                  0
952              61        32        67             15                  0

     liveness_%  speechiness_%  \
0             8              4
1            10              4
2            31              6
3            11             15
4            11              6
..          ...            ...
948           8              3
949          12              6
950           8              6
951          12              5
952          11              5

                                             cover_url
0                                            Not Found
1    https://i.scdn.co/image/ab67616d0000b2730656d5...
2    https://i.scdn.co/image/ab67616d0000b273e85259...
3    https://i.scdn.co/image/ab67616d0000b273e787cf...
4    https://i.scdn.co/image/ab67616d0000b273ab5c9c...
..                                                 ...
948  https://i.scdn.co/image/ab67616d0000b2730f5397...
949  https://i.scdn.co/image/ab67616d0000b273e0b60c...
950                                          Not Found
951                                          Not Found
952  https://i.scdn.co/image/ab67616d0000b273992a1f...

[953 rows x 25 columns]>

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    int64
 18  valence_%             953 non-null    int64
 19  energy_%              953 non-null    int64
 20  acousticness_%        953 non-null    int64
 21  instrumentalness_%    953 non-null    int64
 22  liveness_%            953 non-null    int64
 23  speechiness_%         953 non-null    int64
 24  cover_url             953 non-null    object
dtypes: int64(17), object(8)
memory usage: 186.3+ KB

In [9]:
df.describe()

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,in_apple_playlists,in_apple_charts,in_deezer_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.00000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000
mean,1.556139,2018.238195,6.033578,13.930745,5200.124869,12.009444,67.812172,51.908709,2.666317,122.540399,66.96957,51.431270,64.279119,27.057712,1.581322,18.213012,10.131165
std,0.893044,11.116218,3.566435,9.201949,7897.608990,19.575992,86.441493,50.630241,6.035599,28.057802,14.63061,23.480632,16.550526,25.996077,8.409800,13.711223,9.912888
min,1.000000,1930.000000,1.000000,1.000000,31.000000,0.000000,0.000000,0.000000,0.000000,65.000000,23.00000,4.000000,9.000000,0.000000,0.000000,3.000000,2.000000
25%,1.000000,2020.000000,3.000000,6.000000,875.000000,0.000000,13.000000,7.000000,0.000000,100.000000,57.00000,32.000000,53.000000,6.000000,0.000000,10.000000,4.000000
50%,1.000000,2022.000000,6.000000,13.000000,2224.000000,3.000000,34.000000,38.000000,0.000000,121.000000,69.00000,51.000000,66.000000,18.000000,0.000000,12.000000,6.000000
75%,2.000000,2022.000000,9.000000,22.000000,5542.000000,16.000000,88.000000,87.000000,2.000000,140.000000,78.00000,70.000000,77.000000,43.000000,0.000000,24.000000,11.000000
max,8.000000,2023.000000,12.000000,31.000000,52898.000000,147.000000,672.000000,275.000000,58.000000,206.000000,96.00000,97.000000,97.000000,97.000000,91.000000,97.000000,64.000000

In [13]:
df.dtypes

track_name              object
artist(s)_name          object
artist_count             int64
released_year            int64
released_month           int64
released_day             int64
in_spotify_playlists     int64
in_spotify_charts        int64
streams                 object
in_apple_playlists       int64
in_apple_charts          int64
in_deezer_playlists     object
in_deezer_charts         int64
in_shazam_charts        object
bpm                      int64
key                     object
mode                    object
danceability_%           int64
valence_%                int64
energy_%                 int64
acousticness_%           int64
instrumentalness_%       int64
liveness_%               int64
speechiness_%            int64
cover_url               object
dtype: object

In [14]:
df.isnull().sum()

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
cover_url                0
dtype: int64

In [15]:
df.nunique()

track_name              943
artist(s)_name          645
artist_count              8
released_year            50
released_month           12
released_day             31
in_spotify_playlists    879
in_spotify_charts        82
streams                 949
in_apple_playlists      234
in_apple_charts         172
in_deezer_playlists     348
in_deezer_charts         34
in_shazam_charts        198
bpm                     124
key                      11
mode                      2
danceability_%           72
valence_%                94
energy_%                 80
acousticness_%           98
instrumentalness_%       39
liveness_%               68
speechiness_%            48
cover_url               535
dtype: int64

In [16]:
 df.sample(5)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,cover_url
528,Lo Siento BB:/ (with Bad Bunny & Julieta Venegas),"Julieta Venegas, Bad Bunny, Tainy",3,2021,10,5,3423,26,775542072,61,...,E,Minor,64,14,70,9,0,9,8,https://i.scdn.co/image/ab67616d0000b273abe9c2...
882,Bad Decisions (with BTS & Snoop Dogg),"Snoop Dogg, BTS, Benny Blanco",3,2022,8,5,1456,0,219196651,53,...,NaN,Major,77,94,87,2,0,23,12,https://i.scdn.co/image/ab67616d0000b2738c47a3...
893,Heartless,Kanye West,1,2008,1,1,17504,34,887906111,63,...,A#,Minor,79,66,65,5,0,25,14,https://i.scdn.co/image/ab67616d0000b273346d77...
278,DESPECHï¿,ROSALï¿½,1,2022,7,28,7613,33,782369383,180,...,G,Major,92,78,62,18,0,6,10,Not Found
722,Monï¿½ï¿½y so,YEAT,1,2021,9,10,1473,0,263779030,2,...,D,Major,69,35,57,12,0,10,9,Not Found

In [17]:
df.value_counts()

track_name                    artist(s)_name       artist_count  released_year  released_month  released_day  in_spotify_playlists  in_spotify_charts  streams    in_apple_playlists  in_apple_charts  in_deezer_playlists  in_deezer_charts  in_shazam_charts  bpm  key  mode   danceability_%  valence_%  energy_%  acousticness_%  instrumentalness_%  liveness_%  speechiness_%  cover_url
ýýýýýýýýýýýýýýýýýýýýý         Fujii Kaze           1             2020           5               20            685                   14                 403097450  24                  94               9                    0                 23                158  F#   Minor  60              52         76        17              0                   19          5              Not Found                                                           1
happier                       Olivia Rodrigo       1             2021           5               21            3069                  4                  850608354  25                  46               105                  0                 45                169  F#   Major  39              36         45        81              0                   8           13             https://i.scdn.co/image/ab67616d0000b273a91c10fe9472d9bd89802e5a    1
golden hour                   JVKE                 1             2022           7               15            4511                  36                 751134527  70                  58               109                  18                230               94   C#   Minor  51              14         59        65              18                  25          3              https://i.scdn.co/image/ab67616d0000b273c2504e80ba2f258697ab2954    1
fukumean                      Gunna                1             2023           5               15            1096                  83                 95217315   60                  210              48                   11                953               130  C#   Minor  85              22         62        12              0                   28          9              https://i.scdn.co/image/ab67616d0000b273017d5e26552345c4b1575b6c    1
favorite crime                Olivia Rodrigo       1             2021           5               21            3681                  0                  783706581  20                  21               99                   0                 7                 173  A    Major  40              19         29        86              0                   34          4              https://i.scdn.co/image/ab67616d0000b273a91c10fe9472d9bd89802e5a    1
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ..
2055                          Sleepy hallow        1             2021           4               14            2226                  0                  624515457  29                  0                44                   0                 0                 161  F#   Minor  78              65         52        46              0                   12          31             https://i.scdn.co/image/ab67616d0000b27378376f650afd63698b82e4b1    1
2 Be Loved (Am I Ready)       Lizzo                1             2022           7               14            3682                  6                  247689123  41                  0                158                  2                 68                156  G    Major  72              92         77        9               0                   8           11             https://i.scdn.co/image/ab67616d0000b273caa75a1b27530c05d8b76675    1
10:35                         Tiï¿½ï¿½sto, Tate M  2             2022           11              1             4942                  26                 325592432  190                 104              147                  18                63                120  G#   Major  70              70         79        7               0                   18          10             Not Found                                                           1
10 Things I Hate About You    Leah Kate            1             2022           3               23            1301                  0                  185550869  23                  1                15                   0                 0                 154  G#   Major  54              45         79        1               0                   17          5              https://i.scdn.co/image/ab67616d0000b273596a9d381ffda7d97da5d702    1
(It Goes Like) Nanana - Edit  Peggy Gou            1             2023           6               15            2259                  59                 57876440   0                   0                109                  17                0                 130  G    Minor  67              96         88        12              19                  8           4              https://i.scdn.co/image/ab67616d0000b2739a8459318ff1a68ecfd74522    1
Name: count, Length: 817, dtype: int64